kind: Secret
apiVersion: v1
metadata:
  name:  {{ include "web-app.fullname" . }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.environment }}/{{ include "web-app.fullname" . }}"
type: Opaque
stringData:
  password: <password>