kind: Secret
apiVersion: v1
metadata:
  name:  {{ include "web-app.fullname" . }}
  annotations:
    avp.kubernetes.io/path: {{ (list .Values.environment (include "web-app.fullname" .) | join "/") }}
type: Opaque
stringData:
  password: <password>