apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sample-app
spec:
  destination:
    name: ''
    namespace: nexus-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: helm
    repoURL: 'git@github.com:mehmetalishaqiri/argocd-sample-app.git'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
  project: default

  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true